/*
 *  Armadillo Workflow Platform v2.0
 *  A simple pipeline system for phylogenetic analysis
 *  
 *  Copyright (C) 2009-2014  Etienne Lord, Mickael Leclercq
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package editor;


import biologic.seqclasses.InformationJDialog;
import biologic.*;
import configuration.BlastDBFilter;
import javax.swing.SwingWorker;
import workflows.workflow_properties;
import configuration.Config;
import configuration.Docker;
import configuration.Util;
import database.databaseFunction;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import editor.EditorInterface;
import editor.EditorInterface;
import editors.HelpEditor;
import editors.HelpEditor;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import tools.Toolbox;
import workflows.armadillo_workflow;
import workflows.workflow_properties_dictionnary;

/**
 * Docker Editor
 * Note: Called when it's necessary
 * @author JG
 * @since Jan 2016
 */
public class dockerEditor extends javax.swing.JDialog implements EditorInterface {

    ////////////////////////////////////////////////////////////////////////////
    /// VARIABLES

    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected="";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow parent_workflow;
    InformationJDialog loading;                        //Loading sequence JDialog
    databaseFunction df=new databaseFunction();
    
    ////////////////////////////////////////////////////////////////////////////
    /// CONSTANT

    public final String defaultNameString="Docker";
    public boolean changed=false;
    
    /** Creates new form propertiesJDialog */
    public dockerEditor(java.awt.Frame parent, boolean modal,workflow_properties properties) {
        super(parent, modal);
        this.frame=parent;
        this.properties=properties;
        display(properties);
        updateLists();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        dockerOperatingSystemText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dockerClusterAdvertiseText = new javax.swing.JTextField();
        dockerHttpProxyText = new javax.swing.JTextField();
        dockerOsTypeText = new javax.swing.JTextField();
        dockerServerVersionText = new javax.swing.JTextField();
        dockerNCPUText = new javax.swing.JTextField();
        dockerNFdText = new javax.swing.JTextField();
        dockerInitPathText = new javax.swing.JTextField();
        dockerRootDirText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dockerDriverText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        dockerArchitectureText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        dockerClusterStoreText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        dockerExecutionDriverText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        dockerSocketsText = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        D_AC_StopSelectedCont = new javax.swing.JButton();
        DAC_StopAllCont_button = new javax.swing.JButton();
        D_UI_deleteSelectedImages = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        D_UI_list = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        D_AC_list = new javax.swing.JList();
        ClosejButton = new javax.swing.JButton();
        Update_docker_button = new javax.swing.JButton();
        HelpjButton = new javax.swing.JButton();
        dockerAvailability = new javax.swing.JLabel();

        setTitle("Properties");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        dockerOperatingSystemText.setEditable(false);
        dockerOperatingSystemText.setText("jTextField1");
        dockerOperatingSystemText.setEnabled(false);
        dockerOperatingSystemText.setFocusable(false);

        jLabel1.setText("Parameters");

        jLabel2.setText("ClusterAdvertise");

        jLabel5.setText(" HttpProxy");

        jLabel6.setText("OperatingSystem");

        jLabel7.setText("OsType");

        jLabel10.setText("ServerVersion");

        jLabel11.setText("NCPU");

        jLabel12.setText("NFd");

        jLabel13.setText("InitPath");

        jLabel14.setText("DockerRootDir");

        dockerClusterAdvertiseText.setEditable(false);
        dockerClusterAdvertiseText.setText("jTextField1");
        dockerClusterAdvertiseText.setEnabled(false);
        dockerClusterAdvertiseText.setFocusable(false);
        dockerClusterAdvertiseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dockerClusterAdvertiseTextActionPerformed(evt);
            }
        });

        dockerHttpProxyText.setEditable(false);
        dockerHttpProxyText.setText("jTextField1");
        dockerHttpProxyText.setEnabled(false);
        dockerHttpProxyText.setFocusable(false);

        dockerOsTypeText.setEditable(false);
        dockerOsTypeText.setText("jTextField1");
        dockerOsTypeText.setEnabled(false);
        dockerOsTypeText.setFocusable(false);

        dockerServerVersionText.setEditable(false);
        dockerServerVersionText.setText("jTextField1");
        dockerServerVersionText.setEnabled(false);
        dockerServerVersionText.setFocusable(false);

        dockerNCPUText.setEditable(false);
        dockerNCPUText.setText("jTextField1");
        dockerNCPUText.setEnabled(false);
        dockerNCPUText.setFocusable(false);

        dockerNFdText.setEditable(false);
        dockerNFdText.setText("jTextField1");
        dockerNFdText.setEnabled(false);
        dockerNFdText.setFocusable(false);

        dockerInitPathText.setEditable(false);
        dockerInitPathText.setText("jTextField1");
        dockerInitPathText.setEnabled(false);
        dockerInitPathText.setFocusable(false);

        dockerRootDirText.setEditable(false);
        dockerRootDirText.setText("jTextField1");
        dockerRootDirText.setEnabled(false);
        dockerRootDirText.setFocusable(false);

        jLabel15.setText("Values");

        jLabel16.setText("Driver");

        dockerDriverText.setEditable(false);
        dockerDriverText.setText("jTextField1");
        dockerDriverText.setEnabled(false);
        dockerDriverText.setFocusable(false);

        jLabel17.setText("Architecture");

        dockerArchitectureText.setEditable(false);
        dockerArchitectureText.setText("jTextField1");
        dockerArchitectureText.setEnabled(false);
        dockerArchitectureText.setFocusable(false);

        jLabel18.setText("ClusterStore");

        dockerClusterStoreText.setEditable(false);
        dockerClusterStoreText.setText("jTextField1");
        dockerClusterStoreText.setEnabled(false);
        dockerClusterStoreText.setFocusable(false);
        dockerClusterStoreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dockerClusterStoreTextActionPerformed(evt);
            }
        });

        jLabel19.setText("Execution Driver");

        dockerExecutionDriverText.setEditable(false);
        dockerExecutionDriverText.setText("jTextField1");
        dockerExecutionDriverText.setEnabled(false);
        dockerExecutionDriverText.setFocusable(false);
        dockerExecutionDriverText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dockerExecutionDriverTextActionPerformed(evt);
            }
        });

        jLabel20.setText("Sockets");

        dockerSocketsText.setEditable(false);
        dockerSocketsText.setText("jTextField1");
        dockerSocketsText.setEnabled(false);
        dockerSocketsText.setFocusable(false);
        dockerSocketsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dockerSocketsTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dockerArchitectureText, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dockerClusterStoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dockerSocketsText, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(72, 72, 72)
                                    .addComponent(jLabel15))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dockerDriverText)
                                            .addComponent(dockerOperatingSystemText)
                                            .addComponent(dockerOsTypeText)
                                            .addComponent(dockerServerVersionText)
                                            .addComponent(dockerNCPUText)
                                            .addComponent(dockerNFdText)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dockerRootDirText)
                                            .addComponent(dockerInitPathText)
                                            .addComponent(dockerHttpProxyText)
                                            .addComponent(dockerClusterAdvertiseText, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(18, 18, 18)
                                    .addComponent(dockerExecutionDriverText, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dockerRootDirText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dockerInitPathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dockerHttpProxyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dockerClusterAdvertiseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dockerOperatingSystemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dockerOsTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dockerServerVersionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dockerNCPUText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dockerNFdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(dockerDriverText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(dockerArchitectureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(dockerClusterStoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(dockerExecutionDriverText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(dockerSocketsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Docker Parameters", jPanel1);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Docker uploaded images (Name)");

        jLabel8.setText("Docker Armadillo containers (Name)");

        D_AC_StopSelectedCont.setText("Remove selected container(s)");
        D_AC_StopSelectedCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_AC_StopSelectedContActionPerformed(evt);
            }
        });

        DAC_StopAllCont_button.setText("Remove all containers");
        DAC_StopAllCont_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAC_StopAllCont_buttonActionPerformed(evt);
            }
        });

        D_UI_deleteSelectedImages.setText("Delete Selected image(s)");
        D_UI_deleteSelectedImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_UI_deleteSelectedImagesActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(D_UI_list);

        jScrollPane2.setViewportView(D_AC_list);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(D_AC_StopSelectedCont)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DAC_StopAllCont_button))
                            .addComponent(jLabel3)
                            .addComponent(D_UI_deleteSelectedImages))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(D_UI_deleteSelectedImages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_AC_StopSelectedCont)
                    .addComponent(DAC_StopAllCont_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ClosejButton.setText("Close");
        ClosejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosejButtonActionPerformed(evt);
            }
        });

        Update_docker_button.setText("Update docker");
        Update_docker_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_docker_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Update_docker_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClosejButton)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClosejButton)
                    .addComponent(Update_docker_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Docker Infos", jPanel9);

        HelpjButton.setText("?");
        HelpjButton.setToolTipText("Help / Informations");
        HelpjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpjButtonActionPerformed(evt);
            }
        });

        dockerAvailability.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dockerAvailability.setText("Docker");
        dockerAvailability.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dockerAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HelpjButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HelpjButton)
                    .addComponent(dockerAvailability))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
      
}//GEN-LAST:event_jTabbedPane1ComponentShown

    private void HelpjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpjButtonActionPerformed
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
}//GEN-LAST:event_HelpjButtonActionPerformed

    private void ClosejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosejButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ClosejButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing
    
    private void Update_docker_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_docker_buttonActionPerformed
        // TODO add your handling code here:
        updateLists();
    }//GEN-LAST:event_Update_docker_buttonActionPerformed

    private void D_UI_deleteSelectedImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_UI_deleteSelectedImagesActionPerformed
        // TODO add your handling code here:
        int[] tabInt = this.D_UI_list.getSelectedIndices();
        if (tabInt.length > 0) {
            ArrayList<String> l = new ArrayList<String>();
            for (int i:tabInt){
                String s = this.D_UI_list.getModel().getElementAt(i).toString();
                String[] tp = s.split(", ");
                l.add(tp[0]);
            }
            Docker.removeImagesList(l);
            updateLists();
        }
    }//GEN-LAST:event_D_UI_deleteSelectedImagesActionPerformed

    private void DAC_StopAllCont_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAC_StopAllCont_buttonActionPerformed
        // TODO add your handling code here:
        Docker.stopAllArmadilloContainer();
        Docker.removeAllArmadilloContainer();
        updateLists();
    }//GEN-LAST:event_DAC_StopAllCont_buttonActionPerformed

    private void D_AC_StopSelectedContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_AC_StopSelectedContActionPerformed
        // TODO add your handling code here:
        int[] tabInt = this.D_AC_list.getSelectedIndices();
        if (tabInt.length > 0) {
            ArrayList<String> cont = new ArrayList<String>();
            for (int i:tabInt){
                String s = D_AC_list.getModel().getElementAt(i).toString();
                cont.add(s);
            }
            Docker.removeContainersListFromName(cont);
            updateLists();
        }
    }//GEN-LAST:event_D_AC_StopSelectedContActionPerformed

    private void dockerClusterAdvertiseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dockerClusterAdvertiseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dockerClusterAdvertiseTextActionPerformed

    private void dockerClusterStoreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dockerClusterStoreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dockerClusterStoreTextActionPerformed

    private void dockerExecutionDriverTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dockerExecutionDriverTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dockerExecutionDriverTextActionPerformed

    private void dockerSocketsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dockerSocketsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dockerSocketsTextActionPerformed

    /**
     * Set Lists for D_UI_list or D_AC_list and clean inactives containers
     */
    private void updateLists() {
        D_UI_list.setListData(Docker.getAllImagesNameTab());
        D_AC_list.setListData(Docker.getAllContainersNameListTab());
    }
    
    ///////////////////////////////////////////////////////////////////////////
    /// DISPLAY MAIN FUNCTION

    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);
        setTitle("Docker Informations");
        changed=false; //--For the serialization if needed
        
        // Set position 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width),
					(screenSize.height-d.height));
        
        if (Docker.isDockerHere()){
            addDockerInformation(true);
        } else {
            addDockerInformation(false);
        }
        
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }
    
    
    private void addDockerInformation(boolean b){
        dockerAvailability.setEnabled(b);
        jPanel1.setEnabled(b);
        jPanel9.setVisible(b);
        if (b){
            dockerAvailability.setText("Docker is available");
            dockerAvailability.setForeground(Color.getHSBColor(76, 76, 76));
        } else {
            dockerAvailability.setText("Docker is not available");
            dockerAvailability.setForeground(Color.red);
        }
        dockerClusterAdvertiseText.setText(Docker.getClusterAdvertise());
        dockerOperatingSystemText.setText(Docker.getOperatingSystem());
        dockerHttpProxyText.setText(Docker.getHttpProxy());
        dockerOsTypeText.setText(Docker.getOsType());
        dockerServerVersionText.setText(Docker.getServerVersion());
        dockerNCPUText.setText(Docker.getNCPU());
        dockerNFdText.setText(Docker.getNFd());
        dockerInitPathText.setText(Docker.getInitPath());
        dockerRootDirText.setText(Docker.getRootDirIfDocker());
        dockerArchitectureText.setText(Docker.getArchitecture());
        dockerDriverText.setText(Docker.getDriver());
        dockerClusterStoreText.setText(Docker.getClusterStore());
        dockerExecutionDriverText.setText(Docker.getExecutionDriver());
        dockerSocketsText.setText(Docker.getSockets());
    }
    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds()); 
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
           Config.log("Unable to save "+filename+" dialog image");
        }            
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClosejButton;
    private javax.swing.JButton DAC_StopAllCont_button;
    private javax.swing.JButton D_AC_StopSelectedCont;
    private javax.swing.JList D_AC_list;
    private javax.swing.JButton D_UI_deleteSelectedImages;
    private javax.swing.JList D_UI_list;
    private javax.swing.JButton HelpjButton;
    private javax.swing.JButton Update_docker_button;
    private javax.swing.JTextField dockerArchitectureText;
    private javax.swing.JLabel dockerAvailability;
    private javax.swing.JTextField dockerClusterAdvertiseText;
    private javax.swing.JTextField dockerClusterStoreText;
    private javax.swing.JTextField dockerDriverText;
    private javax.swing.JTextField dockerExecutionDriverText;
    private javax.swing.JTextField dockerHttpProxyText;
    private javax.swing.JTextField dockerInitPathText;
    private javax.swing.JTextField dockerNCPUText;
    private javax.swing.JTextField dockerNFdText;
    private javax.swing.JTextField dockerOperatingSystemText;
    private javax.swing.JTextField dockerOsTypeText;
    private javax.swing.JTextField dockerRootDirText;
    private javax.swing.JTextField dockerServerVersionText;
    private javax.swing.JTextField dockerSocketsText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables



}
