/*
*  Armadillo Workflow Platform v1.0
*  A simple pipeline system for phylogenetic analysis
*
*  Copyright (C) 2009-2011  Etienne Lord, Mickael Leclercq
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package editors;


import configuration.Cluster;
import configuration.Cluster;
import editor.DatabaseSQLite3_cellRenderer;
import workflows.workflow_properties;
import configuration.Config;
import configuration.Config;
import configuration.Util;
import configuration.Util;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.File;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import editor.ConnectorInfoBox;
import editor.EditorInterface;
import editor.EditorInterface;
import editor.EditorInterface;
import editor.EditorInterface;
import editor.EditorInterface;
import editors.HelpEditor;
import editors.HelpEditor;
import editors.HelpEditor;
import editors.HelpEditor;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import program.*;
import workflows.Workbox;
import workflows.armadillo_workflow;
import workflows.armadillo_workflow.Workflow;
import workflows.workflow_properties_dictionnary;

/**
 * Editor of the object properties in the Main Workflow
 * Note: Only called if object doesnt have a Custum Editor
 * @author JG
 * @since Feb 2016
 */
public class ClusterEditor extends javax.swing.JDialog implements EditorInterface {
    
    ////////////////////////////////////////////////////////////////////////////
    /// VARIABLES
    
    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected="";             // Selected properties
    Frame frame;
    workflow_properties properties=new workflow_properties();
    armadillo_workflow parent_workflow;
    
    
    
    /** Creates new form propertiesJDialog */
    public ClusterEditor(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        frame=parent;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ClusterName = new javax.swing.JTextField();
        ClusterUserName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ClusterGroupName = new javax.swing.JTextField();
        ClusterAccessAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ClusterNames2_list = new javax.swing.JComboBox();
        ClusterEnabled = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        p2rsa_text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ClusterPWD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClusterModules = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ClusterInfosUpdate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ClosejButton = new javax.swing.JButton();

        setTitle("Properties");

        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setText("Clusters name");

        jLabel6.setText("Selected cluster");

        ClusterName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ClusterName.setText("clustername");
        ClusterName.setMaximumSize(new java.awt.Dimension(251, 27));
        ClusterName.setMinimumSize(new java.awt.Dimension(251, 27));
        ClusterName.setName("ClusterName"); // NOI18N
        ClusterName.setPreferredSize(new java.awt.Dimension(251, 27));
        ClusterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClusterNameActionPerformed(evt);
            }
        });

        ClusterUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ClusterUserName.setText("user name");
        ClusterUserName.setMaximumSize(new java.awt.Dimension(251, 27));
        ClusterUserName.setMinimumSize(new java.awt.Dimension(251, 27));
        ClusterUserName.setName("ClusterUserName"); // NOI18N
        ClusterUserName.setPreferredSize(new java.awt.Dimension(251, 27));
        ClusterUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ClusterUserNameFocusLost(evt);
            }
        });

        jLabel7.setText("User Name");

        jLabel8.setText("Group Name");

        ClusterGroupName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ClusterGroupName.setText("group name");
        ClusterGroupName.setMaximumSize(new java.awt.Dimension(251, 27));
        ClusterGroupName.setMinimumSize(new java.awt.Dimension(251, 27));
        ClusterGroupName.setName("ClusterGroupName"); // NOI18N
        ClusterGroupName.setPreferredSize(new java.awt.Dimension(251, 27));
        ClusterGroupName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ClusterGroupNameFocusLost(evt);
            }
        });

        ClusterAccessAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ClusterAccessAddress.setText("username@(groupName)clustername");
        ClusterAccessAddress.setMaximumSize(new java.awt.Dimension(324, 27));
        ClusterAccessAddress.setMinimumSize(new java.awt.Dimension(324, 27));
        ClusterAccessAddress.setName("ClusterAccessAddress"); // NOI18N
        ClusterAccessAddress.setPreferredSize(new java.awt.Dimension(324, 27));
        ClusterAccessAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClusterAccessAddressActionPerformed(evt);
            }
        });

        jLabel9.setText("Used");

        ClusterNames2_list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mp2_nom@<nom du groupe>-mp2.ccs.usherbrooke.ca", "=== NOT TESTED ====", "Briaree_nom@briaree.calculquebec.ca", "Colosse_nom@colosse.calculquebec.ca", "Cottos_nom@cottos.calculquebec.ca", "Guillimin_nom@guillimin.hpc.mcgill.ca", "Ms2_nom@<nom du groupe>-ms.ccs.usherbrooke.ca" }));
        ClusterNames2_list.setMaximumSize(new java.awt.Dimension(373, 3856));
        ClusterNames2_list.setMinimumSize(new java.awt.Dimension(373, 27));
        ClusterNames2_list.setName("ClusterNames2_list"); // NOI18N
        ClusterNames2_list.setPreferredSize(new java.awt.Dimension(373, 27));
        ClusterNames2_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClusterNames2_listActionPerformed(evt);
            }
        });

        ClusterEnabled.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ClusterEnabled.setText("Cluster is enabled");
        ClusterEnabled.setEnabled(false);
        ClusterEnabled.setName("ClusterEnabled"); // NOI18N

        jTextField1.setText("insert@your.email.com");
        jTextField1.setMaximumSize(new java.awt.Dimension(324, 27));
        jTextField1.setMinimumSize(new java.awt.Dimension(324, 27));
        jTextField1.setPreferredSize(new java.awt.Dimension(324, 27));

        jLabel1.setText("Email");

        jLabel2.setText("Rap ID");

        jTextField2.setText("insert your RapID");
        jTextField2.setMaximumSize(new java.awt.Dimension(324, 27));
        jTextField2.setMinimumSize(new java.awt.Dimension(324, 27));
        jTextField2.setPreferredSize(new java.awt.Dimension(324, 27));

        jLabel3.setText("Path to Privatekey");

        p2rsa_text.setMaximumSize(new java.awt.Dimension(179, 27));
        p2rsa_text.setMinimumSize(new java.awt.Dimension(179, 27));
        p2rsa_text.setName("p2rsa_text"); // NOI18N
        p2rsa_text.setPreferredSize(new java.awt.Dimension(179, 27));
        p2rsa_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                p2rsa_textFocusLost(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p2rsa_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClusterAccessAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClusterEnabled)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ClusterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ClusterGroupName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ClusterUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(ClusterNames2_list, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClusterEnabled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClusterNames2_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClusterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClusterUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClusterGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClusterAccessAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(p2rsa_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        jTabbedPane1.addTab("Cluster Access Options", jPanel9);

        jLabel4.setText("cluster pwd");

        ClusterPWD.setToolTipText("");
        ClusterPWD.setMaximumSize(new java.awt.Dimension(220, 27));
        ClusterPWD.setMinimumSize(new java.awt.Dimension(220, 27));
        ClusterPWD.setName("ClusterPWD"); // NOI18N
        ClusterPWD.setPreferredSize(new java.awt.Dimension(220, 27));

        ClusterModules.setColumns(20);
        ClusterModules.setLineWrap(true);
        ClusterModules.setRows(5);
        jScrollPane1.setViewportView(ClusterModules);

        jLabel10.setText("modules");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClusterPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ClusterPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Informations Saved", jPanel1);

        jButton3.setText("?");
        jButton3.setToolTipText("Help / Informations");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ClusterInfosUpdate.setForeground(new java.awt.Color(255, 116, 0));
        ClusterInfosUpdate.setText("Update Selected Cluster");
        ClusterInfosUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClusterInfosUpdateActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 116, 0));
        jButton2.setText("Test and Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ClosejButton.setForeground(new java.awt.Color(0, 0, 255));
        ClosejButton.setText("<html><b>Close</b></html>");
        ClosejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ClosejButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ClusterInfosUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(ClosejButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClusterInfosUpdate)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ClosejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosejButtonActionPerformed
        //-- 1. Did we change the properties? If, yes ask for direction
        //properties.save();
        //-- 2. Close dialog
        this.setVisible(false);
}//GEN-LAST:event_ClosejButtonActionPerformed
    
    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        
}//GEN-LAST:event_jTabbedPane1ComponentShown
                    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed
        
    private void ClusterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClusterNameActionPerformed
        
    }//GEN-LAST:event_ClusterNameActionPerformed
    
    private void ClusterUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ClusterUserNameFocusLost
        updateName();
        updateValues();
    }//GEN-LAST:event_ClusterUserNameFocusLost
    
    private void ClusterGroupNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ClusterGroupNameFocusLost
        updateGroup();
        updateValues();
    }//GEN-LAST:event_ClusterGroupNameFocusLost
    
    private void ClusterAccessAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClusterAccessAddressActionPerformed
        
    }//GEN-LAST:event_ClusterAccessAddressActionPerformed
    
    private void ClusterInfosUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClusterInfosUpdateActionPerformed
        updateValues();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_ClusterInfosUpdateActionPerformed

    private void ClusterNames2_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClusterNames2_listActionPerformed
        // TODO add your handling code here:
        updateValues();
    }//GEN-LAST:event_ClusterNames2_listActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] pathP2rsa = Util.simpleSearchBox("f",false,false);
        if (pathP2rsa.length == 1 && pathP2rsa[0] != ""){
            properties.put("PathToRSAFile",pathP2rsa[0]);
            p2rsa_text.setText(pathP2rsa[0]);
        } else {
            properties.remove("PathToRSAFile");
            p2rsa_text.setText("path to Private Key");
        }
        updateValues();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void p2rsa_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p2rsa_textFocusLost
        // TODO add your handling code here:
        String s = p2rsa_text.getText();
        if (s.isEmpty()||s==""||s=="path to Private Key"){
            properties.remove("PathToRSAFile");
            p2rsa_text.setText("path to Private Key");
        } else {
            properties.put("PathToRSAFile",s);
            p2rsa_text.setText(s);
        }
        updateValues();
    }//GEN-LAST:event_p2rsa_textFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updateValues();
        boolean b2 = Cluster.getAccessToCluster(properties);
        if (b2) {
            ClusterPWD.setText(properties.get("ClusterPWD"));
            ArrayList<String> tab = Cluster.getModules(properties);
            if (!tab.isEmpty()){
                for (String s : tab) {
                    ClusterModules.append(s);
                    ClusterModules.append("\n");
                }
            }
            String s = Arrays.toString(tab.toArray());
            properties.put("ClusterModules",s);
        } else {
            properties.remove("ClusterModules");
            properties.remove("ClusterPWD");
        }
        jTabbedPane1.setSelectedIndex(1);
        updateValues();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /*
     * Other clusters for the futur
     *     Briaree_nom@briaree.calculquebec.ca
     *     Colosse_nom@colosse.calculquebec.ca
     *     Cottos_nom@cottos.calculquebec.ca
     *     Guillimin_nom@guillimin.hpc.mcgill.ca
     *     Mp2_nom@<nom du groupe>-mp2.ccs.usherbrooke.ca
     *     Ms2_nom@<nom du groupe>-ms.ccs.usherbrooke.ca
     *     Psi_nom@psi.concordia.ca
     */
    
    
    /**
     * General Update
     */
    private void updateValues() {
        ClusterAccessAddress.setEnabled(false);
        ClusterName.setEnabled(false);
        
        int i = this.ClusterNames2_list.getSelectedIndex();
        String s   = (String)this.ClusterNames2_list.getModel().getElementAt(i).toString();
        properties.put("ClusterAllName",s);
        properties.put(ClusterNames2_list.getName(),i);
        if (s.matches("^Mp2.*")||s.matches("^Ms2.*")){
            s = s.replaceAll("\\<nom du groupe\\>","");
            ClusterGroupName.setEnabled(true);
        } else {
            ClusterGroupName.setEnabled(false);
        }
        s = s.replaceAll("^\\w*_nom@","");
        properties.put(ClusterName.getName(),s);
        ClusterName.setText(s);
        ClusterUserName.setEnabled(true);
        updateName();
        updateGroup();
        updateAccess();
        updateEnabled();
    }
    /**
     * Name Update
     */
    private void updateName() {
        String s = ClusterUserName.getText();
        if (s.equals("")||!(properties.isSet(ClusterUserName.getName()))){
            properties.put(ClusterUserName.getName(),"Add a name");
            ClusterUserName.setText("Add a name");
        } else {
            properties.put(ClusterUserName.getName(),s);
            ClusterUserName.setText(s);
        }
    }
    /**
     * Group Update
     */
    private void updateGroup() {
        String s = ClusterGroupName.getText();
        if (s.equals("")||!(properties.isSet(ClusterGroupName.getName()))){
            properties.put(ClusterGroupName.getName(),"Add a group");
            ClusterGroupName.setText("Add a group");
        } else {
            properties.put(ClusterGroupName.getName(),s);
            ClusterGroupName.setText(s);
        }
    }
    /**
     * Access Update
     */
    private void updateAccess() {
        if (properties.isSet("ClusterAllName")) {
            String s       = properties.get("ClusterAllName");
            String group   = "";
            String name    = properties.get(ClusterUserName.getName());
            String cluster = properties.get(ClusterName.getName());
            if (s.matches("^Mp2.*")||s.matches("^Ms2.*"))
                group = properties.get(ClusterGroupName.getName());
            String access  = name+"@"+group+cluster;
            ClusterAccessAddress.setText(access);
            properties.put(ClusterAccessAddress.getName(),access);
            properties.put("Description","Cluster address used:\n"+access+"\nPrivate key path used:\n"+properties.get("PathToRSAFile"));
        }
    }
    
    /**
     * Access Update
     */
    public void updateEnabled(){
        Workbox workbox = parent_workflow.getWorkbox();
        boolean b = Cluster.isClusterEnable(workbox);
        if (b) {
            ClusterEnabled.setSelected(true);
            properties.put(ClusterEnabled.getName(),true);
        } else {
            ClusterEnabled.setSelected(false);
            properties.remove(ClusterEnabled.getName());
        }
    }
    
    /**
     * Load Saved Values
     */
    public void loadSavedValues() {
        ClusterAccessAddress.setEnabled(false);
        ClusterName.setEnabled(false);
        ClusterUserName.setEnabled(false);
        ClusterGroupName.setEnabled(false);
        if (properties.isSet("ClusterAllName")) {
            String s = properties.get("ClusterAllName");
            if (properties.isSet(ClusterName.getName())){
                String s2 = properties.get(ClusterName.getName());
                ClusterName.setText(s2);
            }
            if (properties.isSet(ClusterUserName.getName())){
                String s2 = properties.get(ClusterUserName.getName());
                ClusterUserName.setText(s2);
                ClusterUserName.setEnabled(true);
            }
            if (properties.isSet(ClusterGroupName.getName())){
                String s2 = properties.get(ClusterGroupName.getName());
                ClusterGroupName.setText(s2);
            }
            if (s.matches("^Mp2.*")||s.matches("^Ms2.*")){
                ClusterGroupName.setEnabled(true);
            }
            if (properties.isSet(ClusterNames2_list.getName())){
                int i = Integer.parseInt(properties.get(ClusterNames2_list.getName()));
                ClusterNames2_list.setSelectedIndex(i);
            }
            if (properties.isSet(ClusterAccessAddress.getName())){
                String s2 = properties.get(ClusterAccessAddress.getName());
                ClusterAccessAddress.setText(s2);
            }
            if (properties.isSet(ClusterEnabled.getName())){
                ClusterEnabled.setSelected(true);
            } else {
                ClusterEnabled.setSelected(false);
            }
        } else {
            ClusterNames2_list.setSelectedIndex(0);
            properties.put(ClusterNames2_list.getName(),0);
            ClusterName.setText("Select a cluster");
            ClusterUserName.setText("Add user name");
            ClusterGroupName.setText("Add group name");
            ClusterEnabled.setSelected(false);
        }
        if (properties.isSet("PathToRSAFile")) {
            p2rsa_text.setText(properties.get("PathToRSAFile"));
        }

        if (properties.isSet("ClusterPWD"))
            ClusterPWD.setText(properties.get("ClusterPWD"));
        if (properties.isSet("ClusterModules"))
            ClusterModules.setText(properties.get("ClusterModules"));
        if (properties.isSet("ClusterPWD"))
            ClusterPWD.setText(properties.get("ClusterPWD"));
        if (properties.isSet("ClusterModules"))
            ClusterModules.setText(properties.get("ClusterModules"));
        
        if (properties.isSet("clusterEnabled"))
            ClusterEnabled.setEnabled(Boolean.getBoolean(properties.get("clusterEnabled")));
        else
            ClusterEnabled.setEnabled(false);
        
        
        updateEnabled();
    }
    
    /**
     * This set the Properties
     * @param properties
     */
    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());
//        if (properties.isSet("Description")) this.ClusterAccess.setText(properties.get("Description"));
        loadSavedValues();
    }
    
    ///////////////////////////////////////////////////////////////////////////
    /// DISPLAY MAIN FUNCTION
    
    public void display(workflow_properties properties) {
        initComponents();
        setProperties(properties);
        // Set position
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
                (screenSize.height-d.height)/2);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }
    
    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds());
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
            Config.log("Unable to save "+filename+" dialog image");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClosejButton;
    private javax.swing.JTextField ClusterAccessAddress;
    private javax.swing.JCheckBox ClusterEnabled;
    private javax.swing.JTextField ClusterGroupName;
    private javax.swing.JButton ClusterInfosUpdate;
    private javax.swing.JTextArea ClusterModules;
    private javax.swing.JTextField ClusterName;
    private javax.swing.JComboBox ClusterNames2_list;
    private javax.swing.JTextField ClusterPWD;
    private javax.swing.JTextField ClusterUserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField p2rsa_text;
    // End of variables declaration//GEN-END:variables
}
