/**
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package editors;

import configuration.Config;
import configuration.Util;
import editor.EditorInterface;
import editor.clusterEditorProgram;
import editor.dockerEditorProgram;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import program.*;
import workflows.armadillo_workflow;
import workflows.workflow_properties;
import workflows.workflow_properties_dictionnary;

/**
 *
 * @author : John Doe
 * @Date   : Feb 2016
 */

public class TapirFastEditors extends javax.swing.JDialog implements EditorInterface  {

    /**
     * Creates new form TapirEditors
     */
    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected = "";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow  parent_workflow;

    public final String defaultNameString="Name";
    static final boolean default_map=true;

    public TapirFastEditors(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Buttons = new javax.swing.ButtonGroup();
        how_jButton = new javax.swing.JButton();
        TapirEditors2 = new javax.swing.JTabbedPane();
        general_jPanel1 = new javax.swing.JPanel();
        name_jLabel = new javax.swing.JLabel();
        name_jTextField = new javax.swing.JTextField();
        rename_jButton = new javax.swing.JButton();
        Default_Button = new javax.swing.JRadioButton();
        FS_Advanced_Options_RButton = new javax.swing.JRadioButton();
        FAO_panel = new javax.swing.JPanel();
        FAO__score_Box = new javax.swing.JCheckBox();
        FAO__score_Box_IntValue = new javax.swing.JSpinner();
        FAO__score_Box_Label = new javax.swing.JLabel();
        FAO__mfe_Box = new javax.swing.JCheckBox();
        FAO__mfe_Box_DouValue = new javax.swing.JSpinner();
        FAO__mfe_Box_Label = new javax.swing.JLabel();
        reset_jButton1 = new javax.swing.JButton();
        stop_jButton1 = new javax.swing.JButton();
        run_jButton1 = new javax.swing.JButton();
        close_jButton1 = new javax.swing.JButton();
        docker_jButton = new javax.swing.JButton();
        ClusterProgramButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        how_jButton.setText("?");
        how_jButton.setName("how_jButton"); // NOI18N
        how_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                how_jButton_ActionPerformed(evt);
            }
        });

        TapirEditors2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                TapirEditors2ComponentShown(evt);
            }
        });

        general_jPanel1.setName("general_jPanel1"); // NOI18N
        general_jPanel1.setPreferredSize(new java.awt.Dimension(459, 140));

        name_jLabel.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        name_jLabel.setText("Name");
        name_jLabel.setName("name_jLabel"); // NOI18N

        name_jTextField.setText("Tapir Fast");
        name_jTextField.setName("name_jTextField"); // NOI18N
        name_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_jTextField_ActionPerformed(evt);
            }
        });

        rename_jButton.setText("Rename");
        rename_jButton.setName("rename_jButton"); // NOI18N
        rename_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rename_jButton_ActionPerformed(evt);
            }
        });

        Menu_Buttons.add(Default_Button);
        Default_Button.setText("Default");
        Default_Button.setName("Default_Button"); // NOI18N
        Default_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Default_Button_ActionPerformed(evt);
            }
        });

        Menu_Buttons.add(FS_Advanced_Options_RButton);
        FS_Advanced_Options_RButton.setText("FS Advanced Options");
        FS_Advanced_Options_RButton.setName("FS_Advanced_Options_RButton"); // NOI18N
        FS_Advanced_Options_RButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FS_Advanced_Options_RButton_ActionPerformed(evt);
            }
        });

        FAO_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("FS_Advanced_Options"));

        FAO__score_Box.setText("score");
        FAO__score_Box.setName("FAO__score_Box"); // NOI18N
        FAO__score_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAO__score_Box_ActionPerformed(evt);
            }
        });

        FAO__score_Box_IntValue.setModel(new javax.swing.SpinnerNumberModel(4, 0, 2147483647, 1));
        FAO__score_Box_IntValue.setName("FAO__score_Box_IntValue"); // NOI18N
        FAO__score_Box_IntValue.setPreferredSize(new java.awt.Dimension(115, 28));
        FAO__score_Box_IntValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FAO__score_Box_IntValue_StateChanged(evt);
            }
        });

        FAO__score_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        FAO__score_Box_Label.setText("Int default 4");
        FAO__score_Box_Label.setName("FAO__score_Box_Label"); // NOI18N

        FAO__mfe_Box.setText("mfe");
        FAO__mfe_Box.setName("FAO__mfe_Box"); // NOI18N
        FAO__mfe_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAO__mfe_Box_ActionPerformed(evt);
            }
        });

        FAO__mfe_Box_DouValue.setModel(new javax.swing.SpinnerNumberModel(0.7d, 0.0d, 1.0d, 1.0d));
        FAO__mfe_Box_DouValue.setName("FAO__mfe_Box_DouValue"); // NOI18N
        FAO__mfe_Box_DouValue.setPreferredSize(new java.awt.Dimension(115, 28));
        FAO__mfe_Box_DouValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FAO__mfe_Box_DouValue_StateChanged(evt);
            }
        });

        FAO__mfe_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        FAO__mfe_Box_Label.setText("default (0.70) mfe ratio cutoff");
        FAO__mfe_Box_Label.setName("FAO__mfe_Box_Label"); // NOI18N

        javax.swing.GroupLayout FAO_panelLayout = new javax.swing.GroupLayout(FAO_panel);
        FAO_panel.setLayout(FAO_panelLayout);
        FAO_panelLayout.setHorizontalGroup(
            FAO_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FAO_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FAO_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FAO__score_Box)
                    .addComponent(FAO__mfe_Box))
                .addGap(18, 18, 18)
                .addGroup(FAO_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FAO_panelLayout.createSequentialGroup()
                        .addComponent(FAO__score_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FAO__score_Box_Label))
                    .addGroup(FAO_panelLayout.createSequentialGroup()
                        .addComponent(FAO__mfe_Box_DouValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FAO__mfe_Box_Label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FAO_panelLayout.setVerticalGroup(
            FAO_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FAO_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FAO_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FAO__score_Box)
                    .addComponent(FAO__score_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FAO__score_Box_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FAO_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FAO__mfe_Box)
                    .addComponent(FAO__mfe_Box_DouValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FAO__mfe_Box_Label))
                .addContainerGap())
        );

        FAO__score_Box.getAccessibleContext().setAccessibleDescription("Score");
        FAO__score_Box_IntValue.getAccessibleContext().setAccessibleDescription("Score");
        FAO__mfe_Box.getAccessibleContext().setAccessibleDescription("Free Energy Ratio");
        FAO__mfe_Box_DouValue.getAccessibleContext().setAccessibleDescription("Free Energy Ratio");

        reset_jButton1.setForeground(new java.awt.Color(255, 116, 0));
        reset_jButton1.setText("Reset");
        reset_jButton1.setMaximumSize(new java.awt.Dimension(91, 29));
        reset_jButton1.setMinimumSize(new java.awt.Dimension(91, 29));
        reset_jButton1.setName("reset_jButton"); // NOI18N
        reset_jButton1.setPreferredSize(new java.awt.Dimension(91, 29));
        reset_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_jButton1_ActionPerformed(evt);
            }
        });

        stop_jButton1.setForeground(new java.awt.Color(0, 0, 255));
        stop_jButton1.setText("Stop");
        stop_jButton1.setMaximumSize(new java.awt.Dimension(91, 29));
        stop_jButton1.setMinimumSize(new java.awt.Dimension(91, 29));
        stop_jButton1.setName("stop_jButton"); // NOI18N
        stop_jButton1.setPreferredSize(new java.awt.Dimension(91, 29));
        stop_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop_jButton1_ActionPerformed(evt);
            }
        });

        run_jButton1.setForeground(new java.awt.Color(255, 116, 0));
        run_jButton1.setText("RUN");
        run_jButton1.setMaximumSize(new java.awt.Dimension(91, 29));
        run_jButton1.setMinimumSize(new java.awt.Dimension(91, 29));
        run_jButton1.setName("run_jButton"); // NOI18N
        run_jButton1.setPreferredSize(new java.awt.Dimension(91, 29));
        run_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_jButton1_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout general_jPanel1Layout = new javax.swing.GroupLayout(general_jPanel1);
        general_jPanel1.setLayout(general_jPanel1Layout);
        general_jPanel1Layout.setHorizontalGroup(
            general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(general_jPanel1Layout.createSequentialGroup()
                .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(general_jPanel1Layout.createSequentialGroup()
                        .addComponent(name_jLabel)
                        .addGap(18, 18, 18)
                        .addComponent(name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rename_jButton))
                    .addComponent(FAO_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(general_jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(general_jPanel1Layout.createSequentialGroup()
                                .addComponent(reset_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stop_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(run_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(general_jPanel1Layout.createSequentialGroup()
                                .addComponent(Default_Button)
                                .addGap(18, 18, 18)
                                .addComponent(FS_Advanced_Options_RButton)))))
                .addGap(5, 5, 5))
        );
        general_jPanel1Layout.setVerticalGroup(
            general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(general_jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_jLabel)
                    .addComponent(name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rename_jButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stop_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(run_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Default_Button)
                    .addComponent(FS_Advanced_Options_RButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FAO_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        name_jTextField.getAccessibleContext().setAccessibleDescription("");
        rename_jButton.getAccessibleContext().setAccessibleDescription("");
        Default_Button.getAccessibleContext().setAccessibleDescription("");
        FS_Advanced_Options_RButton.getAccessibleContext().setAccessibleDescription("");

        TapirEditors2.addTab("Tapir Fast Editors", general_jPanel1);

        close_jButton1.setForeground(new java.awt.Color(0, 0, 255));
        close_jButton1.setText("Close");
        close_jButton1.setMaximumSize(new java.awt.Dimension(91, 29));
        close_jButton1.setMinimumSize(new java.awt.Dimension(91, 29));
        close_jButton1.setName("close_jButton"); // NOI18N
        close_jButton1.setPreferredSize(new java.awt.Dimension(91, 29));
        close_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_jButton1_ActionPerformed(evt);
            }
        });

        docker_jButton.setText("Docker");
        docker_jButton.setMaximumSize(new java.awt.Dimension(91, 29));
        docker_jButton.setMinimumSize(new java.awt.Dimension(91, 29));
        docker_jButton.setName("docker_jButton"); // NOI18N
        docker_jButton.setPreferredSize(new java.awt.Dimension(91, 29));
        docker_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docker_jButton_ActionPerformed(evt);
            }
        });

        ClusterProgramButton.setText("Cluster");
        ClusterProgramButton.setMaximumSize(new java.awt.Dimension(91, 29));
        ClusterProgramButton.setMinimumSize(new java.awt.Dimension(91, 29));
        ClusterProgramButton.setPreferredSize(new java.awt.Dimension(91, 29));
        ClusterProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClusterProgramButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(close_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(docker_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClusterProgramButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(how_jButton))
            .addGroup(layout.createSequentialGroup()
                .addComponent(TapirEditors2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClusterProgramButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(docker_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(close_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(how_jButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TapirEditors2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, Short.MAX_VALUE))
        );

        how_jButton.getAccessibleContext().setAccessibleDescription("http://bioinformatics.psb.ugent.be/webtools/tapir/");
        TapirEditors2.getAccessibleContext().setAccessibleName("TapirEditors");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TapirEditors2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TapirEditors2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_TapirEditors2ComponentShown
        
    private void how_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_how_jButton_ActionPerformed
        // TODO add your handling code here:
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
    }//GEN-LAST:event_how_jButton_ActionPerformed

    private void rename_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rename_jButton_ActionPerformed
        // TODO add your handling code here:
        properties.put("Name", this.name_jTextField.getText());
    }//GEN-LAST:event_rename_jButton_ActionPerformed

    private void name_jTextField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_jTextField_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_jTextField_ActionPerformed
    

    private void Default_Button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Default_Button_ActionPerformed
        // TODO add your handling code here:
        if (properties.isSet(Default_Button.getName()) &&
            properties.isSet(FS_Advanced_Options_RButton.getName())
        ){
            properties.remove(Default_Button.getName());
            Default_Button.setSelected(false);

            properties.remove(FS_Advanced_Options_RButton.getName());
        }
        Util.buttonEventSpinner(properties,Default_Button,null);
        menuFields(properties);
    }//GEN-LAST:event_Default_Button_ActionPerformed

    private void FS_Advanced_Options_RButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FS_Advanced_Options_RButton_ActionPerformed
        // TODO add your handling code here:
        if (properties.isSet(Default_Button.getName()) &&
            properties.isSet(FS_Advanced_Options_RButton.getName())
        ){
            properties.remove(Default_Button.getName());
            Default_Button.setSelected(false);

            properties.remove(FS_Advanced_Options_RButton.getName());
        }
        Util.buttonEventSpinner(properties,FS_Advanced_Options_RButton,null);
        menuFields(properties);
    }//GEN-LAST:event_FS_Advanced_Options_RButton_ActionPerformed

    private void FAO__score_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAO__score_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,FAO__score_Box,FAO__score_Box_IntValue);
    }//GEN-LAST:event_FAO__score_Box_ActionPerformed

    private void FAO__score_Box_IntValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FAO__score_Box_IntValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,FAO__score_Box,FAO__score_Box_IntValue);
    }//GEN-LAST:event_FAO__score_Box_IntValue_StateChanged

    private void FAO__mfe_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAO__mfe_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,FAO__mfe_Box,FAO__mfe_Box_DouValue);
    }//GEN-LAST:event_FAO__mfe_Box_ActionPerformed

    private void FAO__mfe_Box_DouValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FAO__mfe_Box_DouValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,FAO__mfe_Box,FAO__mfe_Box_DouValue);
    }//GEN-LAST:event_FAO__mfe_Box_DouValue_StateChanged

    private void close_jButton1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_jButton1_ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_close_jButton1_ActionPerformed

    private void docker_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docker_jButton_ActionPerformed
        // TODO add your handling code here:
        dockerEditorProgram dock = new dockerEditorProgram(this.frame, false, properties);
        dock.setVisible(true);
    }//GEN-LAST:event_docker_jButton_ActionPerformed

    private void ClusterProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClusterProgramButtonActionPerformed
        // TODO add your handling code here:
        clusterEditorProgram clus = new clusterEditorProgram(this.frame, false, properties);
        clus.setVisible(true);
    }//GEN-LAST:event_ClusterProgramButtonActionPerformed

    private void reset_jButton1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_jButton1_ActionPerformed
        // TODO add your handling code here:
        properties.load();             //--reload current properties from file
        this.setProperties(properties);//--Update current field
        //this.display(properties);
        this.setVisible(false);
    }//GEN-LAST:event_reset_jButton1_ActionPerformed

    private void stop_jButton1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop_jButton1_ActionPerformed
        // TODO add your handling code here:
        properties.put("Status", Config.status_nothing);
        properties.killThread();
    }//GEN-LAST:event_stop_jButton1_ActionPerformed

    private void run_jButton1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_jButton1_ActionPerformed
        // TODO add your handling code here:
        if (this.properties.isSet("ClassName")){
            this.parent_workflow.workflow.updateDependance();
            programs prog=new programs(parent_workflow.workbox.getCurrentWorkflows());
            prog.Run(properties);
        }
    }//GEN-LAST:event_run_jButton1_ActionPerformed
    /*******************************************************************
    * Enabled Function
    *******************************************************************/
    
    private void enabledFunctionForFS_Advanced_Options(boolean e) {
        this.FAO__score_Box.setEnabled(e);
        if (properties.isSet(FAO__score_Box.getName()) && e==true) {
            this.FAO__score_Box_IntValue.setEnabled(true);
        } else {
            this.FAO__score_Box_IntValue.setEnabled(false);
        }

        this.FAO__mfe_Box.setEnabled(e);
        if (properties.isSet(FAO__mfe_Box.getName()) && e==true) {
            this.FAO__mfe_Box_DouValue.setEnabled(true);
        } else {
            this.FAO__mfe_Box_DouValue.setEnabled(false);
        }

    }
    

    /*******************************************************************
    * Update Saved Properties => usp_functions
    *******************************************************************/

    private void updateSavedProperties(workflow_properties properties) {
        usp_valueANDtext (properties);
        usp_boxANDbutton (properties);
    }
    
    private void usp_valueANDtext (workflow_properties properties) {
        if (properties.isSet(FAO__score_Box_IntValue.getName())){
            this.FAO__score_Box_IntValue.setValue(Integer.parseInt(properties.get(FAO__score_Box_IntValue.getName())));
            this.FAO__score_Box_IntValue.setEnabled(false);
        }
        if (properties.isSet(FAO__mfe_Box_DouValue.getName())){
            this.FAO__mfe_Box_DouValue.setValue(Double.parseDouble(properties.get(FAO__mfe_Box_DouValue.getName())));
            this.FAO__mfe_Box_DouValue.setEnabled(false);
        }
    }
    
    private void usp_boxANDbutton (workflow_properties properties) {
        if (properties.isSet(FAO__score_Box.getName())){
            this.FAO__score_Box.setSelected(true);
            this.FAO__score_Box_IntValue.setEnabled(true);
        }
        if (properties.isSet(FAO__mfe_Box.getName())){
            this.FAO__mfe_Box.setSelected(true);
            this.FAO__mfe_Box_DouValue.setEnabled(true);
        }
    }
    

    /*******************************************************************
     * Set the configuration properties for this object
     ******************************************************************/

    @Override
    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);
        // Set position
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
                (screenSize.height-d.height)/2);
        
        // Set the program properties
        this.setProperties(properties);
        
        // Update Saved Properties => usp
        this.updateSavedProperties(properties);
        
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }

    /*******************************************************************
     * Sets for Properties
     ******************************************************************/

    /**
     * Set Properties
     * @param properties
     */

    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());
        //if (this.properties.isSet("Description")) this.Notice.setText(properties.get("Description"));
        
        // Properties Default Options
        this.defaultPgrmValues(properties);
        // Set the menu
        this.menuFields(properties);
    }

    public void setProperties(String filename, String path) {
        workflow_properties tmp=new workflow_properties();
        tmp.load(filename, path);
        this.properties=tmp;
        setTitle(properties.getName());
    }

    /*******************************************************************
     * Set With default program values present in properties file
     ******************************************************************/
    private void defaultPgrmValues(workflow_properties properties) {
        boolean b = true;
        if (!(properties.isSet(Default_Button.getName()))
        && !(properties.isSet(FS_Advanced_Options_RButton.getName()))
        ) {
            b = false;
        }
        
        Util.getDefaultPgrmValues(properties,b);
    }
    
    /*******************************************************************
     * Set Menu fields
     ******************************************************************/

    private void menuFields(workflow_properties properties) {
        if (properties.isSet(Default_Button.getName())) {
            Default_Button.setSelected(true);
            enabledFunctionForFS_Advanced_Options(false);
        }
        else if (properties.isSet(FS_Advanced_Options_RButton.getName())) {
            FS_Advanced_Options_RButton.setSelected(true);
            enabledFunctionForFS_Advanced_Options(true);
        }
    }

    /*******************************************************************
     * Save Image
     ******************************************************************/

    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds());
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
            Config.log("Unable to save "+filename+" dialog image");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClusterProgramButton;
    private javax.swing.JRadioButton Default_Button;
    private javax.swing.JCheckBox FAO__mfe_Box;
    private javax.swing.JSpinner FAO__mfe_Box_DouValue;
    private javax.swing.JLabel FAO__mfe_Box_Label;
    private javax.swing.JCheckBox FAO__score_Box;
    private javax.swing.JSpinner FAO__score_Box_IntValue;
    private javax.swing.JLabel FAO__score_Box_Label;
    private javax.swing.JPanel FAO_panel;
    private javax.swing.JRadioButton FS_Advanced_Options_RButton;
    private javax.swing.ButtonGroup Menu_Buttons;
    private javax.swing.JTabbedPane TapirEditors2;
    private javax.swing.JButton close_jButton1;
    private javax.swing.JButton docker_jButton;
    private javax.swing.JPanel general_jPanel1;
    private javax.swing.JButton how_jButton;
    private javax.swing.JLabel name_jLabel;
    private javax.swing.JTextField name_jTextField;
    private javax.swing.JButton rename_jButton;
    private javax.swing.JButton reset_jButton1;
    private javax.swing.JButton run_jButton1;
    private javax.swing.JButton stop_jButton1;
    // End of variables declaration//GEN-END:variables
    }

